function stack2tiffmultichan(stack,datadir,stackname)
% Function saves data as 16bit multichannel stack
filename = fullfile(datadir,[stackname '.tiff']);
chans = size(stack,3);
fiji_descr = ['ImageJ=1.52p' newline ...
            'images=' num2str(size(stack,3)*...
                              size(stack,4)*...
                              size(stack,5)) newline... 
            'channels=' num2str(size(stack,3)) newline...
            'slices=' num2str(size(stack,4)) newline...
            'frames=' num2str(size(stack,5)) newline...
            'hyperstack=true' newline...
            'mode=rgb' newline...  
            'composite=true' newline...
            'loop=false' newline...  
            'min=0.0' newline...      
            'max=25'];
t = Tiff(filename,'w');
tagstruct.ImageLength = size(stack,1);
tagstruct.ImageWidth = size(stack,2);
tagstruct.Photometric = Tiff.Photometric.MinIsBlack;
tagstruct.BitsPerSample = 16;
tagstruct.SamplesPerPixel = 1;
tagstruct.Compression = Tiff.Compression.LZW;
tagstruct.PlanarConfiguration = Tiff.PlanarConfiguration.Chunky;
tagstruct.SampleFormat = Tiff.SampleFormat.UInt;
tagstruct.ImageDescription = fiji_descr;
for frame = 1:size(stack,5)
    for slice = 1:size(stack,4)
        for channel = 1:size(stack,3)
            t.setTag(tagstruct)
            t.write(im2uint16(stack(:,:,channel,slice,frame)));
            t.writeDirectory(); % saves a new page in the tiff file
        end
    end
end
t.close() 
end